### ISSUE TITLE
how to get message history (message archiving) using jabber-net

### ISSUE THREAD

**Issue by Dases95** [xmppo/Jabber-Net#106]
I'm making simple XMPP client using Jabber-Net. To send simple message, i need a simple example on how to retrieve message history?

**Comment by ForNeVeR** [comment]
Hello. As Jabber-Net currently has no direct support of that feature, you'll have to use the low-level features to make it work. Quick look at [XEP-0313](https://xmpp.org/extensions/xep-0313.html) makes me think you'll need to prepare special IQ queries and send them to the server. Jabber-Net has the low-lever infrastructure to do that.

You could also take a look at the [How do I add my own packet types?](https://fornever.github.io/Jabber-Net/FAQ_Packets.html) FAQ entry.

**Comment by Dases95** [comment]
i have to create an "YourQuery"  object  and put the special IQ queries as a parameter ?

**Comment by ForNeVeR** [comment]
`YourQuery` itself is a special IQ query.

**Comment by Dases95** [comment]
how to set the type of the IQ using `yourQuery` and how to send this query to the server

**Comment by ForNeVeR** [comment]
What do you mean by the "type of the IQ"? IQ _is_ one of the packet types in the XMPP protocol. And you, the user, should fill it with the data you need.

To send it (or any packet actually) to the server, you should call `XmppStream.Write`. One example of `XmppStream` you're probably familiar with is a `JabberClient`.

**Comment by Dases95** [comment]
Could you give me a example on how to use the `XmppStream.Write` ?

**Comment by Dases95** [comment]
i tried this  but no result appear
```
private void j_OnStreamInit(object sender, ElementStream stream)
		{
			XmlDocument doc = new XmlDocument();
			doc.InnerXml = "<query xmlns = 'urn:xmpp:mam:2'><x xmlns = 'jabber:x:data' type = 'submit'><field var = 'FORM_TYPE' type = 'hidden'><value> urn:xmpp:mam:2 </value></field><field var ='with' ><value>admin@DESKTOP-MUBI565</value></field></x></query>";
			YourQuery myQuery = new YourQuery(doc);
			XmppStream x = (XmppStream)sender;
			x.Write(myQuery);
			stream.AddFactory(new MyFactory());
		}
```

**Comment by ForNeVeR** [comment]
Which result do you expect?

**Comment by Dases95** [comment]
the response of the server including the messaeges history

**Comment by Dases95** [comment]
the responce from the server

**Comment by Dases95** [comment]
The response from the server

**Comment by ForNeVeR** [comment]
And how do you observe the response from the server?
