### ISSUE TITLE
Sending extra messages

### ISSUE THREAD

**Issue by nitkinz** [xmppo/Jabber-Net#75]
Hello.  I use version 2.1.2.  I create JabberClient and start sending messages.  If forced to terminate the program.  It closes and the idea to send messages should cease but somehow taken last I came back and sent to the recipient and it all takes place after the close of the program almost immediately.  If you could somehow solve this problem it would be great.

**Comment by nitkinz** [comment]
though perhaps not a problem and you

**Comment by ForNeVeR** [comment]
Could you please clarify the report? And maybe show some code to reproduce the issue?

**Comment by ForNeVeR** [comment]
_(Hint: if you're able to describe the problem in Russian, I will help to solve it as well.)_

**Comment by nitkinz** [comment]
Можно наверно закрыть, проблема проявляется даже после перезагрузки компьютера и работе только наших сервисов. Будем искать дальше.

**Comment by ForNeVeR** [comment]
Ок. Если окажется, что всё-таки баг Jabber-Net — обращайтесь.
