### ISSUE TITLE
SASL EXTERNAL mechanism

### ISSUE THREAD

**Issue by EliotWealth** [xmppo/Jabber-Net#86]
Hello!
After openfire released a new version with fixed OF-1173 (https://issues.igniterealtime.org/browse/OF-1173), server started to offer EXTERNAL mechanism by default.
Which is not working in jabber-net.

Is there any EXTERNAL mechanism fix?

----------
Quick fix.
https://github.com/EliotWealth/Jabber-Net/pull/1
Change mechanisms priority.
Fill missing qop directive.

**Comment by ForNeVeR** [comment]
Hello, @EliotWealth, and thanks for the bug report and for the information.

I'm away for a couple of days, but I hope I'll be able to sort everything out at start of the next week. Sorry for the delay.
