### ISSUE TITLE
Stuck on disconnect in Example

### ISSUE THREAD

**Issue by tree1891** [xmppo/Jabber-Net#96]
In JabberNet.Example, trying disconnect make app stuck.

**Comment by ForNeVeR** [comment]
Hello. Could you please provide some details? It definitely doesn't stuck in my tests. What server are you using? What about the connection mode?

**Comment by tree1891** [comment]
openfire 4.2.2
connection type: Socket
noSSL
noProxy

OS: Windows 10 Pro 1709 x64

**Comment by ForNeVeR** [comment]
Alright, sorry for the (long) delay. I was able to reproduce the issue, and that means I'll fix it!
